# Generated by Django 5.1.2 on 2024-11-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_complete',
        ),
    ]
