# Generated by Django 5.1.2 on 2024-12-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_connectionrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
