# Generated by Django 5.1.2 on 2024-12-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_student_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='rate',
        ),
        migrations.AddField(
            model_name='teacher',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
